server:
    port: 8080
cxf:
    path: /api
    jaxrs:
        component-scan: true
        classes-scan-packages: org.apache.cxf.jaxrs.swagger
spring:
    datasource:
        url: jdbc:h2:file:../data/database
        username: sa
        password: sa